# lints, and then runs Lighthouse CI (Google) for performance checks

name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'pnpm'

      - name: Check formatting
        run: |
          pnpm install --frozen-lockfile
          pnpm check
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build:staging
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      - name: run Lighthouse CI
        run: |
          sudo yarn global add @lhci/cli@0.4.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}