name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main, dev]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IS_PRODUCTION: ${{ endsWith(github.ref, 'main') }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Can use secrets manager in GH instead
      - name: Build Admin!
        run: pnpm build:staging
        env:
          VITE_FIREBASE_API_KEY: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_API_KEY || secrets.DEV_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_AUTH_DOMAIN || secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_DATABASE_URL || secrets.DEV_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_PROJECT_ID || secrets.DEV_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_STORAGE_BUCKET || secrets.DEV_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_MESSAGING_SENDER_ID || secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_APP_ID || secrets.DEV_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ env.IS_PRODUCTION == 'true' && secrets.DEV_FIREBASE_MEASUREMENT_ID || secrets.DEV_FIREBASE_MEASUREMENT_ID }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.IS_PRODUCTION == 'true' && secrets.FIREBASE_SERVICE_ACCOUNT_NWPLUS_UBC || secrets.FIREBASE_SERVICE_ACCOUNT_NWPLUS_UBC_DEV }}
          channelId: live
          projectId: ${{ env.IS_PRODUCTION == 'true' && 'nwplus-ubc-dev' || 'nwplus-ubc-dev' }} # same for now -- just as the environment variables above are; when changing, ensure that prod repo secrets on GH are added